object Versions {

    const val CORE = "1.7.0"
    const val LIFE_CYCLE = "2.4.1"
    const val APP_COMPAT = "1.5.0"
    const val ANDROID_MATERIAL = "1.6.1"
    const val FRAGMENT_VERSION = "1.4.0"
    const val ACTIVITY_VERSION = "1.4.0"
    const val NAVIGATION_VERSION = "2.3.5"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val GRADLE_PLUGIN = "7.0.4"
    const val KOTLIN_VERSION = "1.5.20"
    const val ANDROID_LIFECYCLE = "2.4.0"
    const val HILT_VERSION = "2.40.5"
    const val HILT_WORK= "1.0.0"
    const val COROUTINES = "1.6.0"
    const val ROOM_DB = "2.4.0"
    const val TIMBER = "5.0.1"
    const val GSON = "2.9.0"
    const val MSAL = "2.2.3"
    const val intuit = "2.2.3"
    const val INTUIT_SDP_SSP = "1.0.6"
    const val RETROFIT = "2.8.0"
    const val SPAN = "1.7"
    const val DEXTER = "6.2.3"
    const val WORK = "2.7.1"
    const val MAP_BOX = "10.5.0"
    const val GOOGLE_PLAY_SERVICE = "18.0.0"
    const val COIL = "2.1.0"
    const val GLIDE = "4.13.0"
    const val SHIMMER = "0.5.0"
    const val SWIPE="1.1.0"


}